name: release
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - master
  #     - main
  #   paths:
  #     - "SA-Rapid7Assets/**"

permissions:
  contents: write

jobs:
  call-packaging-workflow:
    uses: ZachTheSplunker/app-wfa/.github/workflows/release.yml@main
    with:
      package-name: SA-Rapid7Assets